<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net40;net10.0-windows</TargetFrameworks>
    <NoWarn>WFDEV006;CA1416</NoWarn>
  </PropertyGroup>

  <PropertyGroup>
    <RootNamespace>DevForge</RootNamespace>
    <AssemblyName>DevForge.UI</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <PropertyGroup>
    <Deterministic>False</Deterministic>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\*.ico" />
    <EmbeddedResource Include="Resources\*.png" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DevForge.Base\DevForge.Base.n.csproj" />
  </ItemGroup>

</Project>
