<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net20;net40;net10.0-windows</TargetFrameworks>
    <NoWarn>WFDEV006;CA1416</NoWarn>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <PropertyGroup>
    <RootNamespace>Pva2cpa</RootNamespace>
    <AssemblyName>Pva2cpa</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <PropertyGroup>
    <Deterministic>False</Deterministic>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net20'">
    <Reference Include="System.Windows.Forms" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Pva2cpa.Lib\Pva2cpa.Lib.n.csproj" />
  </ItemGroup>

</Project>
