<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net40;net10.0</TargetFrameworks>
    <NoWarn>NU1510</NoWarn>
  </PropertyGroup>

  <PropertyGroup>
    <RootNamespace>DevForge.Lib</RootNamespace>
    <AssemblyName>DevForge.Lib</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

</Project>
