<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net40;net10.0</TargetFrameworks>
    <NoWarn>NU1510;CA1416</NoWarn>
  </PropertyGroup>

  <PropertyGroup>
    <RootNamespace>MemForge.Lib</RootNamespace>
    <AssemblyName>MemForge.Lib</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Hexer.Lib">
      <HintPath>..\deps\net40\Hexer.Lib.dll</HintPath>
    </Reference>
    <Reference Include="Vanara.Core">
      <HintPath>..\deps\fx40\Vanara.Core.dll</HintPath>
    </Reference>
    <Reference Include="Vanara.PInvoke.Shared">
      <HintPath>..\deps\fx40\Vanara.PInvoke.Shared.dll</HintPath>
    </Reference>
    <Reference Include="Vanara.PInvoke.Kernel32">
      <HintPath>..\deps\fx40\Vanara.PInvoke.Kernel32.dll</HintPath>
    </Reference>
    <Reference Include="Vanara.PInvoke.User32">
      <HintPath>..\deps\fx40\Vanara.PInvoke.User32.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'net40'">
    <Reference Include="System.Management" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'net10.0'">
    <PackageReference Include="System.Management" Version="10.0.9" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\DevForge.Base\DevForge.Base.n.csproj" />
  </ItemGroup>

</Project>
